// ==UserScript==
// @name          Gitlab Dark
// @namespace     http://userstyles.org
// @description	  A dark theme for the website https://gitlab.com
// @author        2E0PGS
// @homepage      https://userstyles.org/styles/133416
// @include       http://gitlab.com/*
// @include       https://gitlab.com/*
// @include       http://*.gitlab.com/*
// @include       https://*.gitlab.com/*
// @run-at        document-start
// @version       0.20170201191004
// ==/UserScript==
(function() {var css = [
	"/* Userstyle for Gitlab.com. Created by: 2E0PGS */",
	"/* Repository: https://bitbucket.org/2E0PGS/userstyles/overview */",
	"/* Licence: GNU v3 */",
	"/* Userstyle URL: todo /*",
	"/* Version 1.0.7 01/02/2017 18:33*/",
	"",
	"/* I suggest you set your Syntax Highlighting Theme to \"Dark\" under your /profile/preferences Page.*/",
	"",
	"body, h1, h2, h3, h4, h5, h6, .wiki h1, .wiki h2, .wiki h3, .wiki h4, .wiki p, .wiki, .md-page, .blog-entry h1, .blog-entry h2, .blog-entry h3, .blog-entry h4, .blog-entry h5, .md-page h1, .md-page h2, .md-page h3, .md-page h4, .md-page h5, .blog-entry p, .md-page p, .detail-page-description .title, p, .cover-block .cover-title, .cover-block .cover-desc {",
	"	color: #ffffff !important;	",
	"}",
	"",
	"body, .full-post {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	"body.navless {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	"hr {",
	"	border-top: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Nav Bar--- */",
	"header.navbar-gitlab, .row-content-block.content-component-block, .commit-header, .navbar-default {",
	"	background-color: #1c1e22 !important;",
	"	border-bottom: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Icon for notifications--- */",
	"header.navbar-gitlab .container-fluid .nav>li>a {",
	"	color: rgba(224, 224, 224, 0.84) !important;",
	"}",
	"",
	"/* ---Seems the Nav links got broken in recent update. May need to remove legacy version of this--- */",
	".nav-links li a, header .header-content .title a, .project-stats .nav>li>a {",
	"	color: rgb(255, 255, 255) !important;",
	"}",
	"",
	".project-stats .nav>li>a:hover, .project-stats .nav>li>a:focus, .nav-links li a:hover {",
	"	color: rgba(185, 185, 185, 0.88) !important;",
	"}",
	"",
	".cover-block {",
	"	background-color: #1e2125 !important;",
	"}",
	"",
	".nav-links {",
	"	border-bottom: 1px solid #696969 !important;",
	"}",
	"",
	".row-content-block.white {",
	"	background-color: #1e2125 !important;",
	"}",
	"",
	".content-wrapper .container-fluid {",
	"	background-color: #1e2125 !important;",
	"}",
	"",
	".row-content-block {",
	"	border-top: 1px solid #1e2125 !important;",
	"	border-bottom: 1px solid #1e2125 !important;",
	"	color: #959494 !important;",
	"}",
	"",
	"/* ---Left Side Nav Bar--- */",
	"body.ui_charcoal .page-with-sidebar .sidebar-wrapper {",
	"	background: #1c1e22 !important;",
	"}",
	"",
	"/* ---Left Side Nav Bar Button--- */",
	"header.navbar-gitlab .side-nav-toggle {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	"header.navbar-gitlab .side-nav-toggle:hover {",
	"	background-color: rgba(255,255,255,0.05) !important;",
	"}",
	"",
	"/* ---Event Items--- */",
	".event-item a {",
	"	color: #EEEEEE !important;",
	"}",
	"",
	".event-item .event-title {",
	"	color: #CDCDCD !important;",
	"}",
	"",
	".event-item {",
	"	color: #b1b1b1;",
	"	border-bottom: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Search--- */",
	".dropdown-menu-toggle {",
	"	background-color: #272b2f !important;",
	"	color: #ffffff !important;",
	"}",
	"",
	".dropdown-toggle-text.is-default {",
	"	color: rgba(255, 255, 255, 0.99) !important;",
	"}",
	"",
	".form-control, .search form {",
	"	background-color: #272b2f !important;",
	"	border: 0px solid #e5e5e5 !important;",
	"	border-radius: 0px !important;",
	"	color: #fff !important;",
	"}",
	"",
	".dropdown-menu, .dropdown-menu-nav {",
	"	background-color: #1c1e22 !important;",
	"	border: 0px solid rgba(0,0,0,0.1) !important;",
	"}",
	"",
	".dropdown-menu a, .dropdown-menu-nav a {",
	"	color: #fff !important;",
	"}",
	"",
	".dropdown-menu a:hover,.dropdown-menu-nav a:hover {",
	"	background-color: rgba(255,255,255,0.05) !important;",
	"}",
	"",
	"/* ---Hovering Form controls--- */",
	".form-actions, .row-content-block {",
	"	background-color: #1c1e22 !important;",
	"	border-top: 1px solid #696969 !important;",
	"	color: #ffffff !important;",
	"}",
	"",
	"/* ---Code Entry Box--- */",
	".ace-tm, .code.white, .code.white pre.code, .code.white .line_holder .line_content {",
	"	background-color: #1c1e22 !important;",
	"	color: white !important;",
	"}",
	"",
	".ace-tm .ace_gutter, .file-editor .ace_gutter-cell {",
	"	background: #272b2f !important;",
	"	color: #fff !important;",
	"}",
	"",
	".file-holder {",
	"	border: 1px solid #696969 !important;",
	"}",
	"",
	".file-holder .file-title {",
	"	background-color: #1e2125 !important;",
	"	border-bottom: 1px solid #696969 !important;",
	"}",
	"",
	"code {",
	"	color: #fff !important;",
	"	background-color: #343940 !important;",
	"}",
	"",
	"/* ------More Code Viewing and Syntax Tweaks------ */",
	".code.white .line-numbers, .code.white .diff-line-num {",
	"	background-color: #1e2125 !important;",
	"	color: #f0f0f0 !important;",
	"}",
	"",
	".code.white pre.code, .code.white .diff-line-num {",
	"	border-color: #333333 !important;",
	"}",
	"",
	"/* ---Permalink Highlighted line--- */",
	".code.white .line.hll {",
	"	background-color: #333333 !important;",
	"}",
	"",
	"/* ---Syntax Highlighting Tweaks--- */",
	".code.white .line span.k, .code.white .line span.kd {",
	"	color: #80e0e0 !important;",
	"}",
	"",
	".code.white .line span.n, .code.white .line span.nn, .code.white .line span.o {",
	"	color: #f0f0f0 !important;",
	"}",
	"",
	".code.white .line span.kt, .code.white .line span.nc {",
	"	color: #a0a0f0 !important;",
	"}",
	"",
	".code.white .line span.na, .code.white .line span.mi {",
	"	color: #00e080 !important;",
	"}",
	"",
	".code.white .line span.nf {",
	"	color: #ff6060 !important;",
	"}",
	"",
	".code.white .line span.s {",
	"	color: #e050e0 !important;",
	"}",
	"",
	"/* ---Commit Code View Diff Addition Green Background--- */",
	".code.white .line_holder .line_content.new, .code.white .line_holder .diff-line-num.new {",
	"	background-color: #003811 !important;",
	"}",
	"",
	".code.white .line_holder .line_content.new span.idiff {",
	"	background-color: #155627 !important;",
	"}",
	"",
	".code.white .diff-line-num, .code.white .diff-line-num a {",
	"	color: #f0f0f0 !important;",
	"}",
	"",
	"/* ---Commit Code View Diff Deleted Red Background--- */",
	".code.white .line_holder .line_content.old, .code.white .line_holder .diff-line-num.old {",
	"	background-color: #b33f4c !important;",
	"}",
	"",
	".code.white .line_holder .line_content.old span.idiff {",
	"	background-color: #80081a !important;",
	"}",
	"",
	"/* ---Privacy Options of Repo--- */",
	".project-visibility-level-holder .radio .option-title {",
	"	color: #ffffff !important;",
	"}",
	"",
	".project-visibility-level-holder .radio .option-descr {",
	"	color: #b1b1b1 !important;",
	"}",
	"",
	"/* ---Links--- */",
	".nav-links li.active a {",
	"	border-bottom: 2px solid #236dde;",
	"	color: #fff !important;",
	"}",
	"",
	".nav-links li .badge {",
	"	background-color: #424242;",
	"	color: #ffffff !important;",
	"}",
	"",
	"ul.content-list>li a {",
	"	color: #fff !important;",
	"}",
	"",
	"ul.content-list>li {",
	"	color: #b1b1b1 !important;",
	"}",
	"",
	"/* ---Page Controls--- */",
	".pagination>.active>a, .pagination>.active>a:hover, .pagination>.active>a:focus, .pagination>.active>span, .pagination>.active>span:hover, .pagination>.active>span:focus {",
	"	color: #ffffff !important;",
	"	background-color: #272b2f !important;",
	"	border-color: rgba(229, 229, 229, 0) !important;",
	"}",
	"",
	".pagination>li>a, .pagination>li>span {",
	"	color: #9c9b9b !important;",
	"	background-color: #272b2f !important;",
	"	border: 0px solid rgba(229, 229, 229, 0) !important;",
	"}",
	"",
	".pagination>.disabled>span, .pagination>.disabled>span:hover, .pagination>.disabled>span:focus, .pagination>.disabled>a, .pagination>.disabled>a:hover, .pagination>.disabled>a:focus {",
	"	color: #848484 !important;",
	"	background-color: #393e44 !important;",
	"}",
	"",
	"/* ---Avatar Menu Background Fix--- */",
	".nav .open>a, .nav .open>a:hover, .nav .open>a:focus, header.navbar-gitlab .container-fluid .nav>li>a:hover, header.navbar-gitlab .container-fluid .nav>li>a:focus, header.navbar-gitlab .container-fluid .nav>li>a:active, table.table tr th, .file-holder table tr th, .wiki table tr th, .md table tr th, ul.notes .note .note-body .note-text table tr th {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	".layout-nav {",
	"	background: #1c1e22 !important;",
	"	border-bottom: 1px solid #696969;",
	"}",
	"",
	"/* ---Profile Settings--- */",
	".layout-nav .nav-links li.active a, .layout-nav .nav-links li.active i {",
	"	color: #fff !important;",
	"}",
	"",
	".layout-nav .nav-links li a:hover, .layout-nav .nav-links li i:hover {",
	"	color: #fff !important;",
	"}",
	"",
	".provider-btn {",
	"	background-color: #272b2f !important;",
	"}",
	"",
	".provider-btn-group {",
	"	border: 1px solid #3c3c3c !important;",
	"	border-radius: 0px !important;",
	"}",
	"",
	".provider-btn-image {",
	"	border-right: 1px solid #696969 !important;",
	"}",
	"",
	".btn, .snippet-file-content .btn-clipboard {",
	"	border-radius: 0px !important;",
	"	background-color: #1c1e22 !important;",
	"	border-color: #696969 !important;",
	"	color: #ffffff !important;",
	"}",
	"",
	".input-group .input-group-addon {",
	"	background-color: #2e3338 !important;",
	"	color: white !important;",
	"	border: 0px !important;",
	"}",
	"",
	".btn:hover, .snippet-file-content .btn-clipboard:hover, .btn:focus, .snippet-file-content .btn-clipboard:focus {",
	"	background-color: #272b2f !important;",
	"	border-color: #696969 !important;",
	"	color: #ffffff !important;",
	"}",
	"",
	".account-well {",
	"	background-color: #1c1e22 !important;",
	"	border: 1px solid #696969 !important;",
	"}",
	"",
	".well-list>li:hover {",
	"	background: #272b2f !important;",
	"}",
	"",
	".help-block {",
	"	color: rgba(210, 210, 210, 0.85) !important;",
	"}",
	"",
	"/* ---Search Results--- */",
	".well, .search_box {",
	"	background-color: #1c1e22 !important;",
	"	border: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Settings Warning Message--- */",
	".settings-message {",
	"	color: #fc6d26 !important;",
	"	background-color: #000000 !important;",
	"	border: 1px solid #fc6d26 !important;",
	"}",
	"",
	"/* ---Repo Pages--- */",
	".project-home-panel .project-title {",
	"	/* Disabled orange title background due to many complains, I thought it looked good personally */",
	"	/*background-color: #e24329 !important;*/",
	"}",
	"",
	"pre.light-well, pre.description-block {",
	"	border-color: #696969 !important;",
	"}",
	"",
	".light-well, .description-block, pre {",
	"	background-color: #1c1e22 !important;",
	"	color: white !important;",
	"	border-color: #696969 !important;",
	"}",
	"",
	".btn, .snippet-file-content .btn-clipboard {",
	"	background-color: #1c1e22 !important;",
	"	border-color: rgba(229, 229, 229, 0) !important;",
	"	color: #ffffff !important;",
	"}",
	"",
	".project-repo-buttons .count-with-arrow .count, .project-repo-buttons .count-with-arrow .count:hover {",
	"	border-color: rgba(220, 220, 220, 0) !important;",
	"	color: #ffffff !important;",
	"	background: #1c1e22 !important;",
	"}",
	"",
	".nav-links.sub-nav .container-fluid, .nav-links.sub-nav {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	"ul.content-list>li {",
	"	border-color: #696969 !important;",
	"}",
	"",
	"/* ---Commit Network Graph Initial Background Colour--- */",
	".project-network .network-graph {",
	"	background: #444444 !important;",
	"}",
	"",
	"/* ---Last commit--- */",
	".project-last-commit .commit-row-message {",
	"	color: rgba(255, 255, 255, 0.71) !important;",
	"}",
	"",
	"/* ---Repo Settings--- */",
	".bs-callout-info {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	"/* ---Gitlab Issues--- */",
	".board-blank-state, .board-list {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	"ul.notes .system-note {",
	"	background: #1c1e22 !important;",
	"}",
	"",
	".board-header {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	".detail-page-header {",
	"	color: rgba(204, 204, 204, 0.85) !important;",
	"}",
	"",
	".milestone.milestone-closed {",
	"	background: #1e2125 !important;",
	"}",
	"",
	"/* ---Fixes suggested by Daniel Quinn \"/issues/2/\"--- */",
	"board-inner, .dropdown-toggle, .dropdown-menu-toggle {",
	"	border: 1px solid #666666 !important;",
	"}",
	"",
	".board-title {",
	"	border-bottom: 1px solid #666666 !important;",
	"}",
	"",
	".board-issue-count.has-btn {",
	"	border: 0 !important;",
	"}",
	"",
	".issueable-meta, .detail-page-header .identifier, .detail-page-header .author, .discussion-header .author_link, .note-header .author_link, .comment-toolbar, .right-sidebar .title, .toolbar-btn {",
	"	color: #999999 !important;",
	"}",
	"",
	".note-headline-light, .discussion-headline-light, .right-sidebar.right-sidebar-expanded .no-value {",
	"	color: #f7f7f7 !important;",
	"}",
	"",
	"/* ---Mark Down / Wiki--- */",
	".note-textarea {",
	"	color: #ffffff !important;",
	"}",
	".markdown-area {",
	"	background: #1c1e22 !important;",
	"}",
	"",
	".sub-header-block {",
	"	background-color: #1e2125 !important;",
	"	border-bottom: 1px solid #1e2125 !important;",
	"}",
	"",
	"legend {",
	"	border-bottom: 1px solid #696969 !important;",
	"}",
	"",
	".file-editor .editor-ref {",
	"	background: #1c1e22 !important;",
	"	border-right: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Commit List--- */",
	".breadcrumb.repo-breadcrumb a {",
	"	color: #f1f1f1 !important;",
	"}",
	"",
	".commit-row-title .commit-row-message {",
	"	color: #eaeaea !important;",
	"}",
	"",
	".commit .commit-row-info {",
	"	color: #bdbdbd;",
	"	line-height: 1.35 !important;",
	"}",
	"",
	".commit .commit-row-info a {",
	"	color: #717171 !important;",
	"}",
	"",
	".tint-box, #contributors .person .spark, .card {",
	"	background: #1c1e22 !important;",
	"}",
	"",
	"/* ---More Fixes for broken link themeing thanks to recent update--- */",
	".tree-holder .tree-commit .tree-commit-link {",
	"	color: rgba(255, 255, 255, 0.55) !important;",
	"}",
	"",
	".light, .description-block, .tree-holder .tree-time-ago {",
	"	color: rgba(210, 210, 210, 0.85) !important;",
	"}",
	"",
	"/* ---Merges--- */",
	".merge-request.today, .issue.today, .merge-request.closed, .issue.closed, .merge-request.merged, .issue.merged {",
	"	background: #1c1e22 !important;",
	"	border-color: #696969 !important;",
	"}",
	"",
	".mr-state-widget .ci_widget {",
	"	color: rgba(177, 177, 177, 0.85) !important;",
	"}",
	"",
	"/*--- File Names--- */",
	".tree-holder .tree-item .tree-item-file-name i, .tree-holder .tree-item .tree-item-file-name a {",
	"	color: #fff !important;",
	"}",
	"",
	".tree-holder .tree-table tr:hover td {",
	"	background-color: #1c1e22 !important;",
	"	border-top: 1px solid #e24329 !important;",
	"	border-bottom: 1px solid #e24329 !important;",
	"}",
	"",
	".file-holder .file-content {",
	"	background: #1c1e22 !important;",
	"}",
	"",
	".blob-commit-info {",
	"	background: #1c1e22 !important;",
	"	border: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Edit Button--- */",
	".btn-file-option {",
	"	background: linear-gradient(180deg, #020202 25%, #000000 100%) !important;",
	"}",
	"",
	"/* ---Group Repos--- */",
	".cover-block.groups-cover-block {",
	"	background: #1c1e22 !important;",
	"	border-bottom: 1px solid #696969 !important;",
	"}",
	"",
	".cover-block .group-info h1 {",
	"	color: #fff !important;",
	"	background-color: #1e2125 !important;",
	"}",
	"",
	".panel {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	".panel-default>.panel-heading {",
	"	color: #5c5c5c !important;",
	"	background-color: #1c1e22 !important;",
	"	border-color: #696969 !important;",
	"}",
	"",
	".panel-default {",
	"	border-color: #696969 !important;",
	"}",
	"",
	".mr-state-widget {",
	"	background: #1c1e22 !important;",
	"	color: #5c5c5c !important;",
	"	border: 1px solid #696969 !important;",
	"}",
	"",
	".mr-state-widget .ci_widget {",
	"	border-bottom: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Search Filter--- */",
	".search .location-badge {",
	"	color: #e7e9ed !important;",
	"	background-color: #363c42 !important;",
	"}",
	"",
	".right-sidebar {",
	"	background: #1e2125 !important;",
	"	border-left: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Commit List--- */",
	".branch-commit .commit-id, .branch-commit .commit-row-message {",
	"	color: #9c9c9c !important;",
	"}",
	"",
	".commit a, .commit button {",
	"	color: #a0a0a0 !important;",
	"}",
	"",
	".table-holder .builds th {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	".row-content-block.build-content {",
	"	background-color: #1c1e22 !important;",
	"}",
	"",
	"/* ---Footer--- */",
	".panel-footer {",
	"	background-color: #1c1e22 !important;",
	"	border-top: 1px solid #696969 !important;",
	"}",
	"",
	"/* ---Search Box on main website--- */",
	".search-box.is-open .search-input {",
	"	color: black !important;",
	"}",
	"",
	"/* ---delete file confirmation box--- */",
	".modal-content {",
	"	background: #1e2125 !important;",
	"	border: 1px solid #696969 !important;",
	"	color: #ffffff !important;",
	"}",
	"",
	"/* ------Octotree Extension Support Code------ */",
	"",
	"/* ---header--- */",
	".octotree_gitlab_sidebar .octotree_views .octotree_view .octotree_view_header {",
	"	background: #1e2125 !important;",
	"	color: #ffffff !important;",
	"	text-shadow: none !important;",
	"}",
	"",
	".octotree_gitlab_sidebar .octotree_views .octotree_treeview .octotree_header_repo,",
	".octotree_gitlab_sidebar .octotree_views .octotree_treeview .octotree_header_repo a",
	"{",
	"	color: #ffffff !important;",
	"	text-shadow: none !important;",
	"}",
	"",
	".octotree_gitlab_sidebar .octotree_views .octotree_treeview .octotree_header_repo::before {",
	"	color: #ffffff !important;",
	"}",
	"",
	".octotree_gitlab_sidebar a.octotree_opts, .octotree_gitlab_sidebar a.octotree_toggle",
	"{",
	"	color: #c0c0c0 !important;",
	"}",
	"",
	"/* ---main body--- */",
	".octotree_gitlab_sidebar {",
	"	background: #1e2125 !important;",
	"	border-left: 1px solid #696969 !important;",
	"	color: #ffffff !important;",
	"}",
	"",
	"/* ---elements in tree view---*/",
	".octotree_gitlab_sidebar .octotree_views .octotree_treeview .jstree-anchor ",
	"{",
	"	color: #ffffff !important;",
	"}",
	"",
	"/* ---hover over row---*/",
	".jstree-wholerow-hovered {",
	"	background: #333 !important;",
	"}",
	"",
	"/* ---row clicked---*/",
	".jstree-wholerow-clicked {",
	"	background: #182030 !important;",
	"}",
	"",
	"/* ---folder icons---*/",
	".octotree_views .octotree_treeview .jstree-anchor .jstree-icon.tree:before {",
	"	color: #fff !important;",
	"}",
	"",
	"/* ---file icons---*/",
	".octotree_gitlab_sidebar .octotree_views .octotree_treeview .jstree-icon.blob:before {",
	"	color: #ffffff !important;",
	"}",
	"",
	"/* ---folder triangle icons---*/",
	".jstree-icon.jstree-ocl {",
	"	-webkit-filter: invert(100%) hue-rotate(180deg) !important;",
	"	filter: invert(100%) hue-rotate(180deg) !important;",
	"}",
	"",
	"/* ---Fix for active items on Boards--- */",
	"a.label-item.is-focused, li.card.user-can-drag.is-active > h4 > a{",
	"	color: #1c1e22 !important; ",
	"}",
	"",
	"/* ------Pipes------ */",
	".table-holder .ci-table th {",
	"	background-color: #1c1e22 !important;",
	"	color: rgb(255, 255, 255) !important;",
	"}",
	"",
	"/* ---Pipeline Commit ID--- */",
	".pipelines .table.ci-table .pipeline-id, .pipelines .file-holder table.ci-table .pipeline-id, .file-holder .pipelines table.ci-table .pipeline-id, .pipelines .wiki table.ci-table .pipeline-id, .wiki .pipelines table.ci-table .pipeline-id, .pipelines .md table.ci-table .pipeline-id, .md .pipelines table.ci-table .pipeline-id, .pipelines ul.notes .note .note-body .note-text table.ci-table .pipeline-id, ul.notes .note .note-body .note-text .pipelines table.ci-table .pipeline-id {",
	"	color: #b6b6b7 !important;",
	"}"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node); 
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();

// @originalURL	https://gist.github.com/0eeadb6ec204c27aff169846b6212584#file-Gitlab Dark-user-js